function [SO2, Angle, Angle_level, NearestPA, flags] = convexConeSO2_noise...
                        (PA, spectrum_Hb, spectrum_HbO2, F_base, noise_std)
%noise_std is the standard deviation of the noise
    [SO2, Angle, NearestPA, flags] =...
        convexConeSO2(PA ./ noise_std,...
                       spectrum_Hb  ./ noise_std,...
                       spectrum_HbO2./ noise_std...
                       , F_base);
    K = length(PA) - 1;
    NearestPA = NearestPA .* noise_std';
    
    Angle_level = sqrt(2) * (gamma((K + 1)/2) / gamma(K / 2)) / norm(PA ./ noise_std);
end